env:
  global:
    RUST_VERSION=1.15.1

matrix:
  include:
    # Linux
    - os: linux
      dist: trusty
      language: c
      sudo: true
      services:
        - docker

    # OSX
    - os: osx
      language: c
      env:
        - DOTNET_SDK_VERSION=1.0.0-rc4-004771
        - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1

before_script:
  - ./ci/$TRAVIS_OS_NAME/setup.sh

script:
  - ./ci/$TRAVIS_OS_NAME/test.sh