sudo: true
services:
  - docker

env:
  global: DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1

matrix:
  include:
    # Linux
    - os: linux
      dist: trusty
      language: c

    # OSX
    - os: osx
      language: rust
      env:
      - CLI_URL=https://go.microsoft.com/fwlink/?linkid=841692 # rc4-004771 x64

before_script:
  # Install the dotnet cli for osx
  - |
     if [[ "$TRAVIS_OS_NAME" == "osx" ]]; 
       then curl $CLI_URL -L --output dotnet-install.tar.gz &&
       mkdir $HOME/dotnet &&
       tar zxf dotnet-install.tar.gz -C $HOME/dotnet &&
       export PATH=$HOME/dotnet:$PATH; fi

script:
  - ./ci/$($TRAVIS_OS_NAME)/test.sh