sudo: true
services:
  - docker

env:
  global: DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1

matrix:
  include:
    # Linux
    - os: linux
      dist: trusty
      language: c

    # OSX
    - os: osx
      language: rust
      env:
      - DOTNET_SDK_VERSION=1.0.0-rc4-004771

before_script:
  # Install the dotnet cli for osx
  - |
      if [[ "$TRAVIS_OS_NAME" == "osx" ]]; 
        then export DOTNET_SDK_DOWNLOAD_URL=https://dotnetcli.blob.core.windows.net/dotnet/Sdk/$DOTNET_SDK_VERSION/dotnet-dev-osx-x64.$DOTNET_SDK_VERSION.tar.gz &&
        curl -SL $DOTNET_SDK_DOWNLOAD_URL --output dotnet.tar.gz &&
        mkdir $HOME/dotnet &&
        tar zxf dotnet.tar.gz -C $HOME/dotnet &&
        export PATH=$HOME/dotnet:$PATH; fi

script:
  - ./ci/$TRAVIS_OS_NAME/test.sh