env:
  global:
    - RUST_VERSION=1.15.1
    - DOTNET_SDK_VERSION=2.0.0

matrix:
  include:
    # Linux
    - os: linux
      dist: trusty
      language: c
      sudo: true
      services:
        - docker

    # OSX
    - os: osx
      language: c
      env:
        - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1

before_script:
  - ./ci/$TRAVIS_OS_NAME/setup.sh

script:
  - ./ci/$TRAVIS_OS_NAME/test.sh
