sudo: false
language: csharp

env:
  global: DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1

matrix:
  include:
    # Linux
    - os: linux
      dotnet: 1.0.0-rc4-004771

    # OSX
    - os: osx
      dotnet: 1.0.0-rc4-004771

before_script:
  - curl https://sh.rustup.rs -sSf | sh
  - dotnet --info
  - rustc -vV
  - cargo -vV

script:
  - cargo test --verbose
  - cargo build
  - ./target/debug/nuget --test --cargo-build-quiet --cargo-dir ./tests/native/ --nupkg-dir ./tests/feed/
  - cd tests/dotnet
  - dotnet restore --configfile ./Nuget.config
  - dotnet run