environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  RUST_VERSION: rust-1.15.1
  DOTNET_SDK_VERSION: 1.0.1
  matrix:
  - RUST_DOWNLOAD_URL: https://static.rust-lang.org/dist/${RUST_VERSION}-x86_64-pc-windows-msvc.exe
    DOTNET_SDK_DOWNLOAD_URL: https://dotnetcli.blob.core.windows.net/dotnet/Sdk/${DOTNET_SDK_VERSION}/dotnet-dev-win-x64.${DOTNET_SDK_VERSION}.zip

install:
  # .NET CLI
  - ps: Remove-Item "C:\Program Files\dotnet" -recurse -erroraction silentlycontinue
  - ps: Invoke-WebRequest $Env:DOTNET_SDK_DOWNLOAD_URL -OutFile dotnet.zip
  - ps: Expand-Archive dotnet.zip -DestinationPath C:\dotnet
  - ps: $env:PATH="$env:PATH;C:\dotnet"
  # Rust
  - ps: Start-FileDownload $Env:RUST_DOWNLOAD_URL -FileName "rust-stable.exe"
  - ps: .\rust-stable.exe /VERYSILENT /NORESTART /DIR="C:\rust" | Out-Null
  - ps: $env:PATH="$env:PATH;C:\rust\bin"

build: false

test_script:
  # NOTE: This isn't using the ./ci/win/test.ps1 script because cargo prints to stderr
  - dotnet --info
  - rustc -vV
  - cargo -vV

  - cargo test --verbose
  - cargo build

  - ps: .\target\debug\cargo-nuget.exe --test --cargo-build-quiet --cargo-dir .\tests\native\ --nupkg-dir .\tests\feed\

  - dotnet restore .\tests\dotnet\dotnet.csproj --configfile .\Nuget.Config
  - dotnet run --project .\tests\dotnet\dotnet.csproj
