environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  matrix:
  - TARGET: x86_64-pc-windows-msvc
    CLI_URL: https://go.microsoft.com/fwlink/?linkid=841686 # rc4-004771 x64

  - TARGET: i686-pc-windows-msvc
    CLI_URL: https://go.microsoft.com/fwlink/?linkid=841695 # rc4-004771 x86

  - TARGET: x86_64-pc-windows-gnu
    CLI_URL: https://go.microsoft.com/fwlink/?linkid=841686 # rc4-004771 x64

  - TARGET: i686-pc-windows-gnu
    CLI_URL: https://go.microsoft.com/fwlink/?linkid=841695 # rc4-004771 x86

install:
  # .NET Core SDK binaries
  - ps: Start-FileDownload ${env:CLI_URL} -FileName "dotnet-install.exe"
  - ps: .\dotnet-install.exe /install /quiet
  # Rust
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe" -FileName "rust-nightly.exe"
  - ps: .\rust-nightly.exe /VERYSILENT /NORESTART /DIR="C:\rust" | Out-Null
  - ps: $env:PATH="$env:PATH;C:\rust\bin"
  # Results
  - dotnet --version
  - rustc -vV
  - cargo -vV

build: false

build_script:
  - cargo build --verbose
  - ps: cd tests
  - ps: .\test.ps1 -erroraction 'Stop'

test_script:
  - cargo test --verbose
