environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  matrix:
  - RUST_TARGET: x86_64-pc-windows-msvc
    DOTNET_SDK_VERSION: 1.0.0-rc4-004771
    DOTNET_SDK_DOWNLOAD_URL: https://dotnetcli.blob.core.windows.net/dotnet/Sdk/${DOTNET_SDK_VERSION}/dotnet-dev-win-x64.${DOTNET_SDK_VERSION}.zip

install:
  # .NET CLI
  - ps: Get-Command -CommandType Application -ErrorAction SilentlyContinue -Name dotnet | Select-Object -ExpandProperty Definition
  - ps: Invoke-WebRequest $Env:DOTNET_SDK_DOWNLOAD_URL -OutFile dotnet.zip
  - ps: Expand-Archive dotnet.zip -DestinationPath C:\dotnet
  - ps: $env:PATH="$env:PATH;C:\dotnet"
  # Rust
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:RUST_TARGET}.exe" -FileName "rust-nightly.exe"
  - ps: .\rust-nightly.exe /VERYSILENT /NORESTART /DIR="C:\rust" | Out-Null
  - ps: $env:PATH="$env:PATH;C:\rust\bin"

build: false

test_script:
  - dotnet --info
  - rustc -vV
  - cargo -vV

  - cargo test --verbose
  - cargo build

  - ps: .\target\debug\nuget.exe --test --cargo-build-quiet --cargo-dir .\tests\native\ --nupkg-dir .\tests\feed\

  - dotnet restore .\tests\dotnet\dotnet.csproj --configfile .\Nuget.Config
  - dotnet run --project .\tests\dotnet\dotnet.csproj
