environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  RUST_VERSION: rust-1.15.1
  DOTNET_SDK_VERSION: 1.0.1
  matrix:
  - RUST_DOWNLOAD_URL: https://static.rust-lang.org/dist/${RUST_VERSION}-x86_64-pc-windows-msvc.exe
    DOTNET_SDK_DOWNLOAD_URL: https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.ps1

install:
  # .NET CLI
  - ps: Remove-Item "C:\Program Files\dotnet" -recurse -erroraction silentlycontinue
  - ps: mkdir -Force ".\build\" | Out-Null
  - ps: Start-FileDownload $Env:DOTNET_SDK_DOWNLOAD_URL -FileName ".\build\installcli.ps1"
  - ps: .\build\installcli.ps1 -InstallDir C:\dotnet -NoPath -Version $Env:DOTNET_SDK_VERSION
  - ps: $env:Path = "C:\dotnet;$env:Path"
  # Rust
  - ps: Start-FileDownload $Env:RUST_DOWNLOAD_URL -FileName "rust-stable.exe"
  - ps: .\rust-stable.exe /VERYSILENT /NORESTART /DIR="C:\rust" | Out-Null
  - ps: $env:PATH="$env:PATH;C:\rust\bin"

build: false

test_script:
  # NOTE: This isn't using the ./ci/win/test.ps1 script because cargo prints to stderr
  - dotnet --info
  - rustc -vV
  - cargo -vV

  - cargo test --verbose
  - cargo build

  - ps: .\target\debug\cargo-nuget.exe pack --test --cargo-build-quiet --cargo-dir .\tests\native\ --nupkg-dir .\tests\feed\

  - dotnet restore .\tests\dotnet\dotnet.csproj --configfile .\Nuget.Config
  - dotnet run --project .\tests\dotnet\dotnet.csproj
